# @package _global_

defaults:
  - _self_
  - paths: default.yaml
  - hydra: default.yaml

task_name: "demo_traced"

# checkpoint is necessary for demo
# ckpt_path: /workspaces/emlo_Sess4_sol_/Sess4_EMLO_Hydra_/logs/train/runs/2023-10-09_18-47-18/model.script.pt
ckpt_path: src/model.script.pt