_target_: src.models.cifar10_timm_module.CIFAR10TimmModule

optimizer:
  _target_: torch.optim.Adam  #assuming this is the value we got after running optuna
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: timm.create_model
  model_name: resnet18
  pretrained: True 
  num_classes: 10

# compile model for faster training with pytorch 2.0
compile: false
